In [1]:
import numpy as np

In [12]:
l=[1,2,3]
np.array(l)


array([1, 2, 3])

In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.empty((3,3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 2.86558075e-321],
       [1.16825884e-307, 8.90060779e-307, 2.55883494e-307]])

In [12]:
x=np.arange(1,10,2)
x.shape

(5,)

# Airthmetic with ndArray

In [22]:
a=np.random.randn(10)
b=np.random.randn(10)

In [5]:
a

array([ 1.4183614 , -1.21835121, -0.60285999,  0.76067013,  0.21810381,
        0.04758034, -0.30626669,  0.95422328,  0.78458607,  1.26342469])

In [6]:
b

array([-0.19962464,  0.3364493 ,  0.33849667,  1.30672948,  1.97922622,
        1.26170384,  1.37369461,  0.16842516, -0.6892587 , -0.90915131])

In [7]:
a>b

array([ True, False, False, False, False, False, False,  True,  True,
        True])

In [8]:
b>a


array([False,  True,  True,  True,  True,  True,  True, False, False,
       False])

In [9]:
a*100


array([ 141.83614019, -121.83512145,  -60.28599921,   76.067013  ,
         21.81038127,    4.7580336 ,  -30.62666882,   95.42232766,
         78.45860742,  126.34246885])

In [10]:
1/b

array([-5.00940177,  2.97221599,  2.95423885,  0.76526934,  0.50524795,
        0.79257902,  0.72796384,  5.93735518, -1.45083406, -1.09992692])

In [13]:
c=a[a>0]

In [14]:
c

array([1.4183614 , 0.76067013, 0.21810381, 0.04758034, 0.95422328,
       0.78458607, 1.26342469])

In [17]:
d=a[a>b]

In [18]:
d

array([1.4183614 , 0.95422328, 0.78458607, 1.26342469])

# Slicing and Indexing

In [9]:
x=np.ones((7,7))

In [10]:
print(x)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [21]:
x[1:-1:3,1:-1:3]=0

In [19]:
x

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [2]:
x=[9,8,4,2]
np.sqrt(x)

array([3.        , 2.82842712, 2.        , 1.41421356])

In [3]:
y=np.array([9,4,36,49])
np.sqrt(y)

array([3., 2., 6., 7.])

In [4]:
np.power(x,2)

array([81, 64, 16,  4], dtype=int32)

In [5]:
np.power(y,3)

array([   729,     64,  46656, 117649], dtype=int32)

In [10]:
print(np.maximum(x,y))
print(x)
print(y)

[ 9  8 36 49]
[9, 8, 4, 2]
[ 9  4 36 49]


In [12]:
salary=np.array([0,-1,10000,500000])
np.where(salary<=0,'Not Okay','Okay')

array(['Not Okay', 'Not Okay', 'Okay', 'Okay'], dtype='<U8')

# Numerical and statistical methods

In [23]:
m_list=[1,2,3,4,5]
print(m_list)
print(np.mean(m_list))
print(np.cumsum(m_list))
print(np.cumprod(m_list))


[1, 2, 3, 4, 5]
3.0
[ 1  3  6 10 15]
[  1   2   6  24 120]


In [42]:
bool_list=np.array([True,False,False,False,True])
print(bool_list)
#return how many true are present in a boolean array.
print(np.sum(bool_list))
#return true if there is one or more true is present in boolean array
print(np.any(bool_list))
#returns true if all elements ina a oolean array is true
np.all([True,True,True,False])
np.all([np.all([True,True,True,False])])

[ True False False False  True]
2
True


False

In [45]:
unsorted_array=np.array([56,32,1,-9,34,-6])
print(np.sort(unsorted_array))

[-9 -6  1 32 34 56]


In [47]:
np.unique([1,2,4,5,4,3,8,9,0,6,7,5,1,7,435435,65,2,123,3343])

array([     0,      1,      2,      3,      4,      5,      6,      7,
            8,      9,     65,    123,   3343, 435435])


# FILE INPUT/OUTPUT

In [50]:
x=np.arange(0,12,2)
y=np.array([1,3,5,7,9])

In [96]:
np.savez('test',a=x,b=y)

In [97]:
#x=np.load('test.npy')
z=np.load('test.npz')
print(z)

In [99]:
print(z['a'])


[ 0  2  4  6  8 10]


In [5]:
np.save("test",[12,2,3,23,3])
#q=np.load("test.npy")
#print(q)

# LINEAR ALGEBRA FUNCTIONS

In [25]:
a=np.array([[1,1],[3,4]])

In [16]:
x=np.random.randn(3,2)
print(x)

[[-0.89439454 -0.26781031]
 [-0.6705175  -0.38803614]
 [-1.38074914  1.43219375]]


In [17]:
y=np.random.randn(2,3)
print(y)

[[ 0.55647453  0.63609586 -1.81304844]
 [ 0.3493512  -0.82968717  1.58487479]]


In [28]:
round(np.linalg.det(a))


1.0

In [30]:
np.trace(a)

5

In [31]:
np.linalg.inv(a)

array([[ 4., -1.],
       [-3.,  1.]])

In [32]:
a.dot(b)

array([ -4, -21])

In [33]:
np.transpose(a)

array([[1, 3],
       [1, 4]])

In [35]:
diag=np.array([[1,2,3],[4,5,6],[7,8,9]])
d_arr=np.diag(diag)
print(d_arr)

[1 5 9]


In [37]:
converted_sqmatrix=np.diag(d_arr)
print(converted_sqmatrix)

[[1 0 0]
 [0 5 0]
 [0 0 9]]


# Random number generator

In [23]:
np.random.seed(8)

In [24]:
n=np.random.normal(size=(2,2))

In [25]:
u=np.random.uniform(size=(2,2))

In [26]:
n/u

array([[ 0.17449615,  2.28114851],
       [-3.50580285, -2.55131617]])

In [45]:
x=np.ones((5,5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [46]:
x[1:5:2,1:4:2]=0

In [47]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [59]:
y=np.ones((5,5))
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [64]:
y[1:-1,1:-1]=0

In [65]:
y

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [88]:
s=np.array([1,2,3,4,5,6,7,8,9])
t=s.reshape((3,3,-1),order='F')

In [89]:
t

array([[[1],
        [4],
        [7]],

       [[2],
        [5],
        [8]],

       [[3],
        [6],
        [9]]])

In [76]:
t[0][2]

array([7])