In [1]:
import numpy as np

In [3]:
l=[1,2,3]
np.array(l)

array([1, 2, 3])

In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.empty((3,3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 2.86558075e-321],
       [1.16825884e-307, 8.90060779e-307, 2.55883494e-307]])

In [12]:
x=np.arange(1,10,2)
x.shape

(5,)

# Airthmetic with ndArray

In [22]:
a=np.random.randn(10)
b=np.random.randn(10)

In [5]:
a

array([ 1.4183614 , -1.21835121, -0.60285999,  0.76067013,  0.21810381,
        0.04758034, -0.30626669,  0.95422328,  0.78458607,  1.26342469])

In [6]:
b

array([-0.19962464,  0.3364493 ,  0.33849667,  1.30672948,  1.97922622,
        1.26170384,  1.37369461,  0.16842516, -0.6892587 , -0.90915131])

In [7]:
a>b

array([ True, False, False, False, False, False, False,  True,  True,
        True])

In [8]:
b>a


array([False,  True,  True,  True,  True,  True,  True, False, False,
       False])

In [9]:
a*100


array([ 141.83614019, -121.83512145,  -60.28599921,   76.067013  ,
         21.81038127,    4.7580336 ,  -30.62666882,   95.42232766,
         78.45860742,  126.34246885])

In [10]:
1/b

array([-5.00940177,  2.97221599,  2.95423885,  0.76526934,  0.50524795,
        0.79257902,  0.72796384,  5.93735518, -1.45083406, -1.09992692])

In [13]:
c=a[a>0]

In [14]:
c

array([1.4183614 , 0.76067013, 0.21810381, 0.04758034, 0.95422328,
       0.78458607, 1.26342469])

In [17]:
d=a[a>b]

In [18]:
d

array([1.4183614 , 0.95422328, 0.78458607, 1.26342469])

# Slicing and Indexing

In [9]:
x=np.ones((7,7))

In [10]:
print(x)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [21]:
x[1:-1:3,1:-1:3]=0

In [19]:
x

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [2]:
x=[9,8,4,2]
np.sqrt(x)

array([3.        , 2.82842712, 2.        , 1.41421356])

In [3]:
y=np.array([9,4,36,49])
np.sqrt(y)

array([3., 2., 6., 7.])

In [4]:
np.power(x,2)

array([81, 64, 16,  4], dtype=int32)

In [5]:
np.power(y,3)

array([   729,     64,  46656, 117649], dtype=int32)

In [8]:
np.maximum(x,y)
print

array([ 9,  8, 36, 49])