In [2]:
import numpy as np

In [3]:
l=[1,2,3]
np.array(l)

array([1, 2, 3])

In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.empty((3,3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 2.86558075e-321],
       [1.16825884e-307, 8.90060779e-307, 2.55883494e-307]])

In [12]:
x=np.arange(1,10,2)
x.shape

(5,)

NameError: name 'x' is not defined